[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20", features = ["csr"] }
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = { version = "0.4" }
gloo-console = "0.2"
http = "0.2"
wasm-bindgen = "0.2"
time = { version = "0.3", features = ["wasm-bindgen"] }

tonic = { version = "0.8", default-features = false, features = ["codegen", "prost"]}
prost = "0.11"
tonic-web-wasm-client = "0.3"
sha2 = "0.10"

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["prost"] }